#!/usr/bin/python3

# Using SLACK via HTTP request and webhook

import requests
import json
from requests.exceptions import HTTPError

URL="http://quotes.rest/qod.json?category=inspire"
headers={"content-type": "application/json"}

try:
    r=requests.get(URL, headers=headers)
except HTTPError as http_err:
    print(http_err)
except Exception as err:
    print(err)

if r.status_code == 200:
    #print(r.text)
    data=json.loads(r.text)
    for quote in data['contents']['quotes']:
        print(quote['quote'])
        print(quote['author'])
else:
    print("No data returned")
